#SPDX-License-Identifier: MIT-0
---
# tasks file for health
- name: Checking service status for {{ service_name }}
  systemd:
    name: "{{ service_name }}"
  register: service_status
  become: true

- debug:
    msg: "{{ service_status | to_json }}"

- debug:
    msg: "{{ service_name }} service is {{ 'running' if service_status.status.ActiveState == 'active' else 'not running' }}"

#    - name: "Wait for {{ service_name }} to start listening on port 9090"
#      ansible.builtin.wait_for:
#        port: 9090
#        timeout: 30

- name: Verify service healthcheck endpoint is reachable for {{ service_name }}
  ansible.builtin.uri:
    url: "{{ health_endpoint }}"
    method: GET
    status_code: 200
    return_content: true
  register: health_check_result
  until: health_check_result.status == 200
  retries: "{{ healthcheck_retries_count }}" # Number of retry attempts
  delay: "{{ healthcheck_retries_delay }}"    # Delay in seconds between retries
  tags: always

- name: Healthcheck result
  debug:
    msg: "{{ health_check_result.content }}"
