#SPDX-License-Identifier: MIT-0
---
# tasks file for grafana
- name: Host info
  debug:
    msg: "{{ item }}"
  with_items:
    - "FQDN: {{ ansible_facts['fqdn'] }}"
    - "ARCH: {{ ansible_facts['architecture'] }}"
    - "OS: {{ ansible_facts['system'] }}"
    - "Kernel: {{ ansible_facts['kernel'] }}"
    - "OS Family: {{ ansible_facts['os_family'] }}"
    - "Dist: {{ ansible_facts['distribution'] }}"
    - "Dist Version: {{ ansible_facts['distribution_version'] }}"

- name: Defining download URL
  set_fact:
    grafana_download_url: "https://dl.grafana.com/grafana/release/{{ grafana_version }}/grafana_{{ grafana_version }}_20271043721_{{ ansible_facts['system'] | lower }}_{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else ansible_facts['architecture'] | lower }}.tar.gz"

- name: Validating download URL
  debug:
    msg: "grafana_download_url: {{ grafana_download_url }}"

- name: Creating service group
  group:
    name: "{{ grafana_service_group }}"
    state: present
  become: true

- name: Creating service user
  user:
    name: "{{ grafana_service_user }}"
    state: present
  become: true

- name: Preparing folders
  file:
    name: "{{ item }}"
    state: directory
    owner: "{{ grafana_service_user }}"
    group: "{{ grafana_service_group }}"
    mode: '0755'
  become: true
  with_items: 
    - "{{ grafana_install_folder }}"
    - "{{ grafana_config_folder }}"
    - "{{ grafana_data_folder }}"

- name: Download and extract Grafana binary
  ansible.builtin.unarchive:
    src: "{{ grafana_download_url }}"
    dest: "{{ grafana_install_folder }}"
    owner: "{{ grafana_service_user }}"
    group: "{{ grafana_service_group }}"
    mode: '0755'
    remote_src: yes
    extra_opts:
      - '--strip-components=1'
  become: true

- name: Configuring Tempo
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_config_folder }}/grafana.ini"
    owner: "{{ grafana_service_user }}"
    group: "{{ grafana_service_group }}"
    mode: '0755'
  become: true

- name: Creating systemd service file
  template:
    src: grafana.service.j2
    dest: /etc/systemd/system/grafana.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Reloading systemd daemon
  systemd:
    daemon_reload: yes
  become: true

- name: Enabling and starting Grafana service
  systemd:
    name: grafana
    enabled: yes
    state: started 
  become: true

- name: Checking Grafana service status
  systemd:
    name: grafana
  register: grafana_service_status
  become: true

- debug:
    msg: "Grafana service is {{ 'running' if grafana_service_status.status.ActiveState == 'active' else 'not running' }}"
