#SPDX-License-Identifier: MIT-0
---
# defaults file for mimir

base_install_folder: /usr/local/monitoring
mimir_install_folder: "{{ base_install_folder }}/mimir"
mimir_config_folder: /usr/local/monitoring/mimir/config
base_data_folder: /var/lib/monitoring
mimir_data_folder: "{{ base_data_folder }}/mimir"
mimir_service_group: mimir
mimir_service_user: mimir

mimir_http_port: 9009
mimir_grpc_port: 9005
mimir_log_level: info
mimir_storage_bucket_store_dir: "{{ mimir_data_folder }}/tsdb-sync"
mimir_storage_filesystem_dir: "{{ mimir_data_folder }}/fs/tsdb"
mimir_storage_tsdb_dir: "{{ mimir_data_folder }}/tmp/tsdb"
mimir_compactor_data_dir: "{{ mimir_data_folder }}/tmp/compactor"
mimir_ruler_storage_dir: "{{ mimir_data_folder }}/tmp/rules"
mimir_storage_tsdb_retention_period: 48h
mimir_compactor_retention_interval: 2h
