---
all:
  hosts:
    rpi5host001.local:
      ansible_host: 192.168.0.185 # eth0
      username: eldius
      vars:
        ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    rpi5host000.local:
      ansible_host: 192.168.0.152 # eth0
      username: eldius
      vars:
        ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  children:
    ollama:
      hosts:
        rpi5host001.local:
    monitoring:
      hosts:
        rpi5host000.local:
    mimir:
      hosts:
        rpi5host000.local:
    prometheus:
      hosts:
        rpi5host000.local:
    grafana:
      hosts:
        rpi5host000.local:
    loki:
      hosts:
        rpi5host000.local:
    alloy:
      hosts:
        rpi5host000.local:
    tempo:
      hosts:
        rpi5host000.local:
