---
all:
  children:
    ollama:
      hosts:
        rpi5host001.local:
          ansible_host: 192.168.0.185
    monitoring:
      hosts:
        rpi5host000.local:
          ansible_host: 192.168.0.152
      vars:
        base_install_folder: /usr/local/monitoring
        base_data_folder: /var/lib/monitoring
  vars:
    ansible_user: "eldius"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
