---
- name: Testing variables
  debug:
    msg:
      "otel_collector_version": "{{ otel_collector_version }}"
      "otel_collector_go_sdk_package_url": "{{ otel_collector_go_sdk_package_url }}"
      "otel_collector_install_arch": "{{ otel_collector_install_arch }}"

- name: Unpacking GO SDK package
  ansible.builtin.unarchive:
    src: "{{ otel_collector_go_sdk_package_url }}"
    dest: "{{ otel_collector_tools_folder }}"
    mode: '0755'
    owner: "{{ otel_collector_service_user }}"
    group: "{{ otel_collector_service_group }}"
    remote_src: true
  become: true
  args:
    creates: "{{ otel_collector_tools_folder }}/go"

- name: Debugging Go version
  shell: "go version"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ otel_collector_tools_folder }}/go/bin"
  register: go_version_res

- name: Debugging Go version
  debug:
    msg: "{{ go_version_res.stdout_lines }}"

- name: Fetching latest version from OTEL Collector Github repo
  ansible.builtin.shell: "curl -s https://api.github.com/repos/open-telemetry/opentelemetry-collector-releases/releases/latest | jq -r .tag_name | sed 's/^v//'"
  register: remote_version_output
  when: otel_collector_version == 'latest' or otel_collector_version | default('') == ''

- name: Defining OTEL Collector version to install
  ansible.builtin.set_fact:
    otel_collector_version: "{{ remote_version_output.stdout }}"
  when: otel_collector_version == 'latest' or otel_collector_version | default('') == ''

- name: Defining OTEL Collector Builder URL
  ansible.builtin.set_fact:
    otel_collector_builder_binary_url: "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv{{ otel_collector_version }}/ocb_{{ otel_collector_version }}_{{ ansible_system|lower }}_{{ otel_collector_install_arch }}"

- name: Downloading OTEL Collector Builder
  ansible.builtin.get_url:
    url: "{{ otel_collector_builder_binary_url }}"
    dest: "{{ otel_collector_tools_folder }}/ocb"
    mode: '0755'
    owner: "{{ otel_collector_service_user }}"
    group: "{{ otel_collector_service_group }}"
  become: true

- name: Generating otelcol-builder.yaml file
  ansible.builtin.template:
    src: otelcol-builder.yaml.j2
    dest: "{{ otel_collector_config_folder }}/otelcol-builder.yaml"
    owner: "{{ otel_collector_service_user }}"
    group: "{{ otel_collector_service_group }}"
    mode: '0755'
  become: true
  register: builder_config_task_res

- name: Building OTEL Collector
  ansible.builtin.shell: "{{ otel_collector_tools_folder }}/ocb --config {{ otel_collector_config_folder }}/otelcol-builder.yaml"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ otel_collector_tools_folder }}/go/bin"
    GOCACHE: "{{ otel_collector_tmp_folder }}"
  register: otelcol_build_res
  become: true
  args:
    creates: "{{ otel_collector_install_folder }}/bin/otelcol"

- name: Changing collector binary ownership
  ansible.builtin.file:
    path: "{{ otel_collector_install_folder }}/bin/otelcol"
    state: file
    owner: "{{ otel_collector_service_user }}"
    group: "{{ otel_collector_service_group }}"
    mode: "0755"
  become: true

- name: Building output
  ansible.builtin.debug:
    msg: "{{ otelcol_build_res.stdout_lines }}"
