---
# tasks file for otel_collector
- name: Host info
  debug:
    msg: "{{ item }}"
  with_items:
    - "FQDN: {{ ansible_facts['fqdn'] }}"
    - "ARCH: {{ ansible_facts['architecture'] }}"
    - "OS: {{ ansible_facts['system'] }}"
    - "Kernel: {{ ansible_facts['kernel'] }}"
    - "OS Family: {{ ansible_facts['os_family'] }}"
    - "Dist: {{ ansible_facts['distribution'] }}"
    - "Dist Version: {{ ansible_facts['distribution_version'] }}"

- name: Creating OTEL Collector service group
  ansible.builtin.group:
    name: "{{ otel_collector_service_group }}"
    state: present
  become: true

- name: Creating OTEL Collector service user
  ansible.builtin.user:
    name: "{{ otel_collector_service_user }}"
    comment: OTEL Collector service user
    home: "{{ otel_collector_install_folder }}"
    group: "{{ otel_collector_service_group }}"
    state: present
    system: true
  become: true

- name: Preparing folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ otel_collector_service_user }}"
    group: "{{ otel_collector_service_group }}"
  become: true
  loop:
    - "{{ otel_collector_install_folder }}"
    - "{{ otel_collector_install_folder }}/bin"
    - "{{ otel_collector_config_folder }}"
    - "{{ otel_collector_data_folder }}"
    - "{{ otel_collector_tools_folder }}"
    - "{{ otel_collector_tmp_folder }}"
  register: create_folders_res

- name: Building OTEL Collector
  ansible.builtin.import_tasks: build_collector.yml

- name: Generating config.yaml file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ otel_collector_config_folder }}/config.yaml"
    owner: "{{ otel_collector_service_user }}"
    group: "{{ otel_collector_service_group }}"
    mode: "0755"
  become: true
  register: config_task_res

- name: Generating environment file
  ansible.builtin.template:
    src: otelcol.conf.j2
    dest: "{{ otel_collector_config_folder }}/otelcol.conf"
    owner: "{{ otel_collector_service_user }}"
    group: "{{ otel_collector_service_group }}"
    mode: "0755"
  become: true
  register: env_task_res

- name: Creating systemd service file
  ansible.builtin.template:
    src: otelcol.service.j2
    dest: /etc/systemd/system/otelcol.service
    owner: root
    group: root
    mode: '0644'
  become: true
  register: servicedef_task_res

- name: Reloading systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Enabling and starting OTEL Collector service
  ansible.builtin.service:
    name: "otelcol"
    state: "started"
    enabled: true
  become: true

- name: Restarting OTEL Collector if config changed
  ansible.builtin.service:
    name: "otelcol"
    state: "restarted"
  when: config_task_res.changed or env_task_res.changed or servicedef_task_res.changed
  become: true

- name: Validating installation
  ansible.builtin.include_tasks: validate.yml
  tags: validate
