#SPDX-License-Identifier: MIT-0
---
- name: Validate Alloy installation
  block:
#    - name: Verify Alloy service is running
#      ansible.builtin.systemd:
#        name: alloy
#      register: alloy_service_check
#      failed_when: alloy_service_check.status.ActiveState != 'active'
#
#    - name: Wait for Alloy to start listening on port {{ alloy_http_listen_port }}
#      ansible.builtin.wait_for:
#        port: "{{ alloy_http_listen_port }}"
#        timeout: 30
#
#    - name: Verify Alloy health endpoint
#      ansible.builtin.uri:
#        url: "http://localhost:{{ alloy_http_listen_port }}/-/ready"
#        method: GET
#        status_code: 200
#      register: alloy_health_check
#      until: alloy_health_check.status == 200
#      retries: 5
#      delay: 2

    - name: Verify service status for Otel Collector
      ansible.builtin.include_role:
        name: health
      vars:
        service_name: otelcol
        health_endpoint: "http://localhost:13133/health/status"

    - name: Check Alloy configuration file exists
      ansible.builtin.stat:
        path: "{{ otel_collector_config_folder }}/otelcol.conf"
      register: alloy_config_stat
      failed_when: not alloy_config_stat.stat.exists

#    - name: Verify OTEL Collector binary exists
#      ansible.builtin.stat:
#        path: "{{ otel_collector_install_folder }}/bin/otelcol"
#      register: alloy_binary_stat
#      failed_when: not alloy_binary_stat.stat.exists
  become: true
