---
# vars file for otel_collector
otel_collector_install_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"

otel_collector_go_sdk_package_url: "https://go.dev/dl/go{{ otel_collector_go_version }}.{{ ansible_system|lower }}-{{ otel_collector_install_arch }}.tar.gz"

otel_collector_builder_install_cmd: "go install go.opentelemetry.io/collector/cmd/builder@v{{ otel_collector_version }}"
