---
- name: Healthcheck OTEL Collector
  hosts: otel_collector
  roles:
    - role: eldius.monitoring_stack_setup.health
      service_name: otelcol
      health_endpoint: "http://localhost:13133/health/status"
