---
- name: Deploy Loki
  hosts: monitoring
  roles:
    - role: eldius.monitoring_stack_setup.health
      service_name: alloy
      health_endpoint: "http://localhost:12345/-/health"
    - role: eldius.monitoring_stack_setup.health
      service_name: loki
      health_endpoint: "http://localhost:3100/ready"
    - role: eldius.monitoring_stack_setup.health
      service_name: grafana
      health_endpoint: "http://localhost:3000/api/health"
