---
- name: Deploy Loki
  hosts: monitoring
  roles:
    - eldius.monitoring_stack_setup.base
    - eldius.monitoring_stack_setup.mimir
    - eldius.monitoring_stack_setup.loki
    - eldius.monitoring_stack_setup.tempo
    - eldius.monitoring_stack_setup.prometheus
    - eldius.monitoring_stack_setup.grafana
    - role: eldius.monitoring_stack_setup.alloy
      when: telemetry_collector | default('alloy') == 'alloy'
    - role: eldius.monitoring_stack_setup.otel_collector
      when: telemetry_collector | default('alloy') == 'otel_collector'
