---
- name: Uninstall Mimir
  hosts: monitoring
  tasks:
    - name: Include Mimir uninstallation tasks
      include_role:
        name: eldius.monitoring_stack_setup.mimir
        tasks_from: uninstall.yml
