---
- name: Uninstall Tempo
  hosts: monitoring
  tasks:
    - name: Include Tempo uninstallation tasks
      include_role:
        name: eldius.monitoring_stack_setup.tempo
        tasks_from: uninstall.yml
