---
- name: Uninstall Prometheus
  hosts: prometheus
  tasks:
    - name: Include Prometheus uninstallation tasks
      include_role:
        name: eldius.monitoring_stack_setup.prometheus
        tasks_from: uninstall.yml
