---
- name: Uninstall Grafana
  hosts: monitoring
  tasks:
    - name: Include Grafana uninstallation tasks
      include_role:
        name: eldius.monitoring_stack_setup.grafana
        tasks_from: uninstall.yml
